theme: minima
title: GitHub Webpage
author: Riya Simha
email: rsimh1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 Blog about communication technology and computer science class.
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
